# Generated by Django 5.2.12 on 2026-03-09 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_type', models.CharField(choices=[('APPLICABILITY', 'NIS2-/KRITIS-Relevanz prüfen'), ('ISO_READINESS', 'ISO-27001-Readiness bewerten'), ('FULL', 'Vollständige ISMS-/NIS2-Gap-Analyse')], default='FULL', max_length=24)),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('IN_PROGRESS', 'In Bearbeitung'), ('COMPLETED', 'Abgeschlossen')], default='DRAFT', max_length=20)),
                ('current_step', models.CharField(choices=[('profile', 'Unternehmensprofil'), ('applicability', 'Betroffenheit'), ('scope', 'Scope & Struktur'), ('maturity', 'Reifegradanalyse'), ('results', 'Ergebnis')], default='profile', max_length=24)),
                ('applicability_result', models.CharField(blank=True, max_length=64)),
                ('applicability_reasoning', models.TextField(blank=True)),
                ('executive_summary', models.TextField(blank=True)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to='organizations.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Kritisch'), ('HIGH', 'Hoch'), ('MEDIUM', 'Mittel'), ('LOW', 'Niedrig')], default='MEDIUM', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_gaps', to='catalog.assessmentdomain')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.assessmentquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_gaps', to='wizard.assessmentsession')),
            ],
            options={
                'ordering': ['severity', 'domain__sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Kritisch'), ('HIGH', 'Hoch'), ('MEDIUM', 'Mittel'), ('LOW', 'Niedrig')], default='MEDIUM', max_length=16)),
                ('effort', models.CharField(choices=[('SMALL', 'Klein'), ('MEDIUM', 'Mittel'), ('LARGE', 'Groß')], default='MEDIUM', max_length=16)),
                ('measure_type', models.CharField(choices=[('ORGANIZATIONAL', 'Organisatorisch'), ('TECHNICAL', 'Technisch'), ('DOCUMENTARY', 'Dokumentarisch')], default='ORGANIZATIONAL', max_length=20)),
                ('target_phase', models.CharField(blank=True, max_length=64)),
                ('owner_role', models.CharField(blank=True, max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('PLANNED', 'Geplant'), ('IN_PROGRESS', 'In Umsetzung'), ('DONE', 'Erledigt')], default='OPEN', max_length=16)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_measures', to='catalog.assessmentdomain')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.assessmentquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_measures', to='wizard.assessmentsession')),
            ],
            options={
                'ordering': ['priority', 'domain__sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DomainScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_raw', models.IntegerField(default=0)),
                ('score_percent', models.PositiveIntegerField(default=0)),
                ('maturity_level', models.CharField(blank=True, max_length=64)),
                ('gap_level', models.CharField(blank=True, max_length=32)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_scores', to='catalog.assessmentdomain')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_scores', to='wizard.assessmentsession')),
            ],
            options={
                'ordering': ['domain__sort_order'],
                'unique_together': {('session', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='SessionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('free_text', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('is_na', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_answers', to='catalog.assessmentquestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_answers', to='catalog.answeroption')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='wizard.assessmentsession')),
            ],
            options={
                'ordering': ['question__sort_order'],
                'unique_together': {('session', 'question')},
            },
        ),
    ]
