version: 2
updates:
  - package-ecosystem: cargo
    directory: /rust/iscy-backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - rust

  - package-ecosystem: docker
    directory: /rust/iscy-backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - ci
