# Generated by Django 5.2.12 on 2026-03-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.CharField(choices=[('ISO27001', 'ISO 27001'), ('NIS2', 'NIS2'), ('CRA', 'Cyber Resilience Act'), ('AI_ACT', 'EU AI Act'), ('IEC62443', 'IEC 62443'), ('ISO_SAE_21434', 'ISO/SAE 21434')], max_length=32)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('guidance', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('evidence_required', models.BooleanField(default=True)),
                ('evidence_guidance', models.TextField(blank=True)),
                ('evidence_examples', models.TextField(blank=True)),
                ('sector_package', models.CharField(blank=True, help_text='Optionales Paket wie DIGITAL, FINANCE, CRITICAL_INFRA, ALL', max_length=64)),
            ],
            options={
                'ordering': ['framework', 'code'],
                'unique_together': {('framework', 'code')},
            },
        ),
    ]
