# Generated by Django 5.2.12 on 2026-03-13 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('requirements_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.CharField(max_length=32)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=32)),
                ('program_name', models.CharField(default='ISCY', max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('ACTIVE', 'Aktiv'), ('SUPERSEDED', 'Ersetzt')], default='ACTIVE', max_length=16)),
                ('effective_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['framework', '-effective_on', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='coverage_level',
            field=models.CharField(choices=[('PRIMARY', 'Primär'), ('SUPPORTING', 'Unterstützend'), ('DERIVED', 'Abgeleitet')], default='PRIMARY', max_length=16),
        ),
        migrations.AddField(
            model_name='requirement',
            name='legal_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='requirement',
            name='mapped_controls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='requirement',
            name='mapping_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='framework',
            field=models.CharField(choices=[('ISO27001', 'ISO 27001'), ('NIS2', 'NIS2'), ('KRITIS', 'KRITIS'), ('CRA', 'Cyber Resilience Act'), ('AI_ACT', 'EU AI Act'), ('IEC62443', 'IEC 62443'), ('ISO_SAE_21434', 'ISO/SAE 21434')], max_length=32),
        ),
        migrations.AddField(
            model_name='requirement',
            name='mapping_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='requirements_app.mappingversion'),
        ),
        migrations.CreateModel(
            name='RegulatorySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.CharField(choices=[('ISO27001', 'ISO 27001'), ('NIS2', 'NIS2'), ('KRITIS', 'KRITIS'), ('CRA', 'Cyber Resilience Act'), ('AI_ACT', 'EU AI Act'), ('IEC62443', 'IEC 62443'), ('ISO_SAE_21434', 'ISO/SAE 21434')], max_length=32)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('authority', models.CharField(max_length=128)),
                ('citation', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('source_type', models.CharField(choices=[('PRIMARY', 'Primärquelle'), ('OFFICIAL_GUIDANCE', 'Offizielle Guidance'), ('STANDARD', 'Standard')], default='PRIMARY', max_length=32)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('effective_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('mapping_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='requirements_app.mappingversion')),
            ],
            options={
                'ordering': ['framework', 'code'],
                'unique_together': {('mapping_version', 'framework', 'code')},
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='primary_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='requirements_app.regulatorysource'),
        ),
        migrations.CreateModel(
            name='RequirementQuestionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strength', models.CharField(choices=[('PRIMARY', 'Primär'), ('SUPPORTING', 'Unterstützend')], default='PRIMARY', max_length=16)),
                ('rationale', models.TextField(blank=True)),
                ('mapping_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_mappings', to='requirements_app.mappingversion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_mappings', to='catalog.assessmentquestion')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_mappings', to='requirements_app.requirement')),
            ],
            options={
                'ordering': ['requirement__framework', 'requirement__code', 'question__sort_order'],
                'unique_together': {('requirement', 'mapping_version', 'question')},
            },
        ),
    ]
