# Generated by Django 5.2.12 on 2026-03-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('wizard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('overall_priority', models.CharField(blank=True, max_length=32)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_plans', to='wizard.assessmentsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_plans', to='organizations.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('objective', models.TextField(blank=True)),
                ('duration_weeks', models.PositiveIntegerField(default=2)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='roadmap.roadmapplan')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(blank=True, max_length=32)),
                ('owner_role', models.CharField(blank=True, max_length=64)),
                ('due_in_days', models.PositiveIntegerField(default=30)),
                ('dependency_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('PLANNED', 'Geplant'), ('IN_PROGRESS', 'In Umsetzung'), ('BLOCKED', 'Blockiert'), ('DONE', 'Erledigt')], default='OPEN', max_length=16)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_tasks', to='wizard.generatedmeasure')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='roadmap.roadmapphase')),
            ],
            options={
                'ordering': ['priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapTaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependency_type', models.CharField(choices=[('FS', 'Finish-to-Start'), ('SS', 'Start-to-Start')], default='FS', max_length=2)),
                ('rationale', models.CharField(blank=True, max_length=255)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='roadmap.roadmaptask')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='roadmap.roadmaptask')),
            ],
            options={
                'ordering': ['predecessor_id', 'successor_id'],
                'unique_together': {('predecessor', 'successor')},
            },
        ),
    ]
