# Generated by Django 5.2.12 on 2026-03-09 14:39

import apps.evidence.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('organizations', '0001_initial'),
        ('requirements_app', '0001_initial'),
        ('wizard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('linked_requirement', models.CharField(blank=True, max_length=128)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/', validators=[apps.evidence.validators.validate_evidence_file])),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('SUBMITTED', 'Zur Prüfung eingereicht'), ('APPROVED', 'Freigegeben'), ('REJECTED', 'Abgelehnt')], default='DRAFT', max_length=16)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='catalog.assessmentdomain')),
                ('measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='wizard.generatedmeasure')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_evidence', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='requirements_app.requirement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_evidence', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='wizard.assessmentsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='organizations.tenant')),
            ],
            options={
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RequirementEvidenceNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('PARTIAL', 'Teilweise abgedeckt'), ('COVERED', 'Abgedeckt')], default='OPEN', max_length=16)),
                ('rationale', models.TextField(blank=True)),
                ('covered_count', models.PositiveIntegerField(default=0)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_needs', to='requirements_app.requirement')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_needs', to='wizard.assessmentsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_needs', to='organizations.tenant')),
            ],
            options={
                'ordering': ['status', 'requirement__framework', 'requirement__code'],
                'unique_together': {('tenant', 'session', 'requirement')},
            },
        ),
    ]
