# Generated by Django 5.2.12 on 2026-03-09 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets_app', '0001_initial'),
        ('organizations', '0001_initial'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_categories', to='organizations.tenant')),
            ],
            options={
                'verbose_name_plural': 'Risk categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('threat', models.TextField(blank=True, help_text='Bedrohungsbeschreibung')),
                ('vulnerability', models.TextField(blank=True, help_text='Schwachstelle die ausgenutzt werden kann')),
                ('impact', models.IntegerField(choices=[(1, '1 – Unerheblich'), (2, '2 – Gering'), (3, '3 – Mittel'), (4, '4 – Hoch'), (5, '5 – Kritisch')], default=3)),
                ('likelihood', models.IntegerField(choices=[(1, '1 – Unwahrscheinlich'), (2, '2 – Selten'), (3, '3 – Moeglich'), (4, '4 – Wahrscheinlich'), (5, '5 – Sehr wahrscheinlich')], default=3)),
                ('residual_impact', models.IntegerField(blank=True, choices=[(1, '1 – Unerheblich'), (2, '2 – Gering'), (3, '3 – Mittel'), (4, '4 – Hoch'), (5, '5 – Kritisch')], null=True)),
                ('residual_likelihood', models.IntegerField(blank=True, choices=[(1, '1 – Unwahrscheinlich'), (2, '2 – Selten'), (3, '3 – Moeglich'), (4, '4 – Wahrscheinlich'), (5, '5 – Sehr wahrscheinlich')], null=True)),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identifiziert'), ('ANALYZING', 'In Analyse'), ('TREATING', 'In Behandlung'), ('ACCEPTED', 'Akzeptiert'), ('MITIGATED', 'Gemindert'), ('TRANSFERRED', 'Transferiert'), ('AVOIDED', 'Vermieden'), ('CLOSED', 'Geschlossen')], default='IDENTIFIED', max_length=16)),
                ('treatment_strategy', models.CharField(blank=True, choices=[('MITIGATE', 'Mindern'), ('ACCEPT', 'Akzeptieren'), ('TRANSFER', 'Transferieren'), ('AVOID', 'Vermeiden')], max_length=16)),
                ('treatment_plan', models.TextField(blank=True)),
                ('treatment_due_date', models.DateField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_risks', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='assets_app.informationasset')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='processes.process')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='organizations.tenant')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='risks.riskcategory')),
            ],
            options={
                'ordering': ['-impact', '-likelihood', 'title'],
            },
        ),
    ]
