# Generated by Django 5.2.12 on 2026-03-09 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('APPLICATION', 'Anwendung'), ('DATA', 'Datenbestand'), ('INFRASTRUCTURE', 'Infrastruktur'), ('SERVICE', 'Service / Plattform'), ('DOCUMENT', 'Dokumentation'), ('OTHER', 'Sonstiges')], default='APPLICATION', max_length=24)),
                ('criticality', models.CharField(choices=[('VERY_HIGH', 'Sehr hoch'), ('HIGH', 'Hoch'), ('MEDIUM', 'Mittel'), ('LOW', 'Niedrig')], default='MEDIUM', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('confidentiality', models.CharField(blank=True, max_length=32)),
                ('integrity', models.CharField(blank=True, max_length=32)),
                ('availability', models.CharField(blank=True, max_length=32)),
                ('lifecycle_status', models.CharField(blank=True, max_length=64)),
                ('is_in_scope', models.BooleanField(default=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='information_assets', to='organizations.businessunit')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_information_assets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_assets', to='organizations.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
