# Generated by Django 5.2.12 on 2026-03-09 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('processes', '0001_initial'),
        ('requirements_app', '0001_initial'),
        ('wizard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicabilityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.CharField(max_length=255)),
                ('company_size', models.CharField(blank=True, max_length=255)),
                ('critical_services', models.TextField(blank=True)),
                ('supply_chain_role', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('RELEVANT', 'Voraussichtlich relevant'), ('POSSIBLY_RELEVANT', 'Möglicherweise relevant'), ('NOT_DIRECTLY_RELEVANT', 'Derzeit nicht direkt relevant')], max_length=32)),
                ('reasoning', models.TextField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicability_assessments', to='organizations.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('FULFILLED', 'Ausreichend erfüllt'), ('PARTIAL', 'Teilweise erfüllt'), ('INFORMAL', 'Informal vorhanden'), ('DOCUMENTED_NOT_IMPLEMENTED', 'Dokumentiert, aber nicht umgesetzt'), ('IMPLEMENTED_NO_EVIDENCE', 'Umgesetzt, aber nicht nachweisbar'), ('MISSING', 'Fehlt vollständig')], default='MISSING', max_length=32)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('evidence_summary', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='processes.process')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='requirements_app.requirement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='organizations.tenant')),
            ],
            options={
                'ordering': ['requirement__framework', 'requirement__code'],
                'unique_together': {('process', 'requirement')},
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('audit_type', models.CharField(choices=[('INTERNAL', 'Internes Audit'), ('EXTERNAL', 'Externes Audit'), ('SURVEILLANCE', 'Ueberwachungsaudit'), ('RECERTIFICATION', 'Rezertifizierungsaudit')], default='INTERNAL', max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Geplant'), ('IN_PROGRESS', 'Laufend'), ('COMPLETED', 'Abgeschlossen'), ('CANCELLED', 'Abgebrochen')], default='PLANNED', max_length=16)),
                ('lead_auditor', models.CharField(blank=True, max_length=255)),
                ('audit_team', models.TextField(blank=True, help_text='Auditteam-Mitglieder, je Zeile ein Name')),
                ('scope', models.TextField(blank=True, help_text='Auditumfang und -kriterien')),
                ('objectives', models.TextField(blank=True)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, help_text='Gesamtfazit des Audits')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audits', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='organizations.tenant')),
            ],
            options={
                'ordering': ['-planned_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding_number', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('MAJOR_NC', 'Hauptabweichung (Major NC)'), ('MINOR_NC', 'Nebenabweichung (Minor NC)'), ('OBSERVATION', 'Beobachtung'), ('OPPORTUNITY', 'Verbesserungspotenzial'), ('POSITIVE', 'Positive Feststellung')], default='MINOR_NC', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('IN_PROGRESS', 'In Bearbeitung'), ('CORRECTIVE_ACTION', 'Korrekturmassnahme definiert'), ('IMPLEMENTED', 'Umgesetzt'), ('VERIFIED', 'Verifiziert / wirksam'), ('CLOSED', 'Geschlossen')], default='OPEN', max_length=20)),
                ('requirement_reference', models.CharField(blank=True, help_text='z.B. A.5.1, NIS2-21-2a', max_length=128)),
                ('evidence_reference', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='assessments.audit')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_findings', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['severity', 'finding_number'],
            },
        ),
        migrations.CreateModel(
            name='ManagementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Management Review', max_length=255)),
                ('status', models.CharField(choices=[('PLANNED', 'Geplant'), ('AGENDA_SET', 'Agenda erstellt'), ('IN_SESSION', 'Sitzung laeuft'), ('PROTOCOL_DRAFT', 'Protokoll-Entwurf'), ('COMPLETED', 'Abgeschlossen')], default='PLANNED', max_length=20)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('attendees', models.TextField(blank=True, help_text='Teilnehmer, je Zeile ein Name/Rolle')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('input_isms_status', models.TextField(blank=True, help_text='Status des ISMS seit letzter Review')),
                ('input_audit_results', models.TextField(blank=True, help_text='Ergebnisse interner/externer Audits')),
                ('input_risk_status', models.TextField(blank=True, help_text='Aktueller Risikostatus und Veraenderungen')),
                ('input_incidents', models.TextField(blank=True, help_text='Sicherheitsvorfaelle und Trends')),
                ('input_metrics', models.TextField(blank=True, help_text='Kennzahlen und Messergebnisse')),
                ('input_feedback', models.TextField(blank=True, help_text='Feedback von interessierten Parteien')),
                ('input_improvement', models.TextField(blank=True, help_text='Moeglichkeiten zur Verbesserung')),
                ('input_changes', models.TextField(blank=True, help_text='Aenderungen die das ISMS betreffen')),
                ('output_decisions', models.TextField(blank=True, help_text='Getroffene Entscheidungen')),
                ('output_actions', models.TextField(blank=True, help_text='Beschlossene Massnahmen mit Verantwortlichen und Fristen')),
                ('output_resource_needs', models.TextField(blank=True, help_text='Ressourcenbedarf')),
                ('output_improvement', models.TextField(blank=True, help_text='Verbesserungsmassnahmen')),
                ('protocol_summary', models.TextField(blank=True, help_text='Zusammenfassung des Protokolls')),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('chairperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_reviews', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_reviews', to='wizard.assessmentsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_reviews', to='organizations.tenant')),
            ],
            options={
                'ordering': ['-review_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('DONE', 'Done')], default='OPEN', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measures', to='assessments.assessment')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measures', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='organizations.tenant')),
            ],
            options={
                'ordering': ['status', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('IN_PROGRESS', 'In Bearbeitung'), ('DONE', 'Erledigt'), ('OVERDUE', 'Ueberfaellig')], default='OPEN', max_length=16)),
                ('completion_notes', models.TextField(blank=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_actions', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='assessments.managementreview')),
            ],
            options={
                'ordering': ['status', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='SoADocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Statement of Applicability', max_length=255)),
                ('version', models.CharField(default='1.0', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('IN_REVIEW', 'In Pruefung'), ('APPROVED', 'Freigegeben')], default='DRAFT', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_soas', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soa_documents', to='wizard.assessmentsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soa_documents', to='organizations.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoAEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_applicable', models.BooleanField(default=True)),
                ('justification', models.TextField(blank=True, help_text='Begruendung fuer Anwendbarkeit oder Ausschluss')),
                ('implementation_status', models.CharField(choices=[('NOT_STARTED', 'Nicht begonnen'), ('PARTIAL', 'Teilweise umgesetzt'), ('IMPLEMENTED', 'Umgesetzt'), ('NOT_APPLICABLE', 'Nicht anwendbar')], default='NOT_STARTED', max_length=20)),
                ('evidence_reference', models.TextField(blank=True, help_text='Verweis auf Evidenzen oder Dokumente')),
                ('notes', models.TextField(blank=True)),
                ('control_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soa_controls', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soa_entries', to='requirements_app.requirement')),
                ('soa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='assessments.soadocument')),
            ],
            options={
                'ordering': ['requirement__framework', 'requirement__code'],
                'unique_together': {('soa', 'requirement')},
            },
        ),
    ]
