# Generated by Django 5.2.12 on 2026-03-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('has_digital_elements', models.BooleanField(default=True)),
                ('includes_ai', models.BooleanField(default=False)),
                ('ot_iacs_context', models.BooleanField(default=False)),
                ('automotive_context', models.BooleanField(default=False)),
                ('support_window_months', models.PositiveIntegerField(default=24)),
                ('regulatory_profile_json', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('component_type', models.CharField(choices=[('APPLICATION', 'Application'), ('LIBRARY', 'Library'), ('SERVICE', 'Service'), ('MODEL', 'AI Model'), ('FIRMWARE', 'Firmware'), ('OTHER', 'Other')], default='APPLICATION', max_length=16)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('is_open_source', models.BooleanField(default=False)),
                ('has_sbom', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_components', to='organizations.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.tenant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='product_security.product')),
            ],
            options={
                'ordering': ['product__name', 'name'],
                'unique_together': {('product', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AISystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('use_case', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('risk_classification', models.CharField(choices=[('NONE', 'Keine besondere AI-Risiko-Klasse'), ('LIMITED', 'Begrenztes Risiko'), ('HIGH', 'High-Risk / erhöhte Governance'), ('GPAI', 'General Purpose AI / Modellbezug')], default='NONE', max_length=16)),
                ('in_scope', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.tenant')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_systems', to='product_security.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product_security.productfamily'),
        ),
        migrations.CreateModel(
            name='ProductSecuritySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cra_applicable', models.BooleanField(default=False)),
                ('ai_act_applicable', models.BooleanField(default=False)),
                ('iec62443_applicable', models.BooleanField(default=False)),
                ('iso_sae_21434_applicable', models.BooleanField(default=False)),
                ('cra_readiness_percent', models.PositiveIntegerField(default=0)),
                ('ai_act_readiness_percent', models.PositiveIntegerField(default=0)),
                ('iec62443_readiness_percent', models.PositiveIntegerField(default=0)),
                ('iso_sae_21434_readiness_percent', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='product_security.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('methodology', models.CharField(blank=True, default='STRIDE / ad hoc', max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_models', to='product_security.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.tenant')),
            ],
            options={
                'ordering': ['product__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('cve', models.CharField(blank=True, max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Kritisch'), ('HIGH', 'Hoch'), ('MEDIUM', 'Mittel'), ('LOW', 'Niedrig')], default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('MITIGATED', 'Mitigiert'), ('FIXED', 'Behoben'), ('ACCEPTED', 'Akzeptiert')], default='OPEN', max_length=16)),
                ('remediation_due', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerabilities', to='product_security.component')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='product_security.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.tenant')),
            ],
            options={
                'ordering': ['product__name', 'severity', 'title'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'name')},
        ),
        migrations.CreateModel(
            name='ProductRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PLANNED', 'Geplant'), ('ACTIVE', 'Aktiv'), ('MAINTENANCE', 'Wartung'), ('EOL', 'End of Life')], default='PLANNED', max_length=16)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('support_end_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='product_security.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='organizations.tenant')),
            ],
            options={
                'ordering': ['product__name', '-release_date', '-created_at'],
                'unique_together': {('product', 'version')},
            },
        ),
    ]
