from dataclasses import dataclass, field
from typing import Dict, List


@dataclass(frozen=True)
class SectorDefinition:
    code: str
    label: str
    nis2_group: str                     # Anhang I / Anhang II / Nicht zugeordnet
    nis2_annex: str = ''                # 'I' oder 'II' fuer maschinelle Auswertung
    indicative_classification: str = ''
    score_bonus: int = 0
    reasoning: str = ''
    downstream_impact: str = ''
    roadmap_focus: List[str] = field(default_factory=list)
    key_domains: List[str] = field(default_factory=list)
    special_regime: str = ''
    kritis_related: bool = False
    # F03: Expliziter Hinweis, dass KRITIS sektorspezifische Schwellenwerte erfordert
    kritis_note: str = ''


SECTOR_DEFINITIONS: List[SectorDefinition] = [
    SectorDefinition(
        code="ENERGY",
        label="Energie",
        nis2_group="Anhang I – hohe Kritikalitaet",
        nis2_annex='I',
        indicative_classification="Regelmaessig besonders wichtig / KRITIS-nah",
        score_bonus=6,
        reasoning="Energie zaehlt in der NIS-2-Systematik zu den Sektoren mit hoher Kritikalitaet und ist in Deutschland regelmaessig KRITIS-nah.",
        downstream_impact="Der Prozess fokussiert staerker auf Resilienz, BCM, physische Sicherheit, Lieferkette und Incident-Meldewege.",
        roadmap_focus=["Resilienz und Wiederanlauf", "Melde- und Eskalationswege", "Lieferkettenkontrollen"],
        key_domains=["BCM", "INC", "SUP", "PHYS", "DETECT"],
        kritis_related=True,
        kritis_note="KRITIS-Schwellenwerte nach BSI-KritisV Anhang 1 beachten (z.B. 500 MW Nennleistung).",
    ),
    # F04: Wasserstoff explizit als Unterkategorie
    SectorDefinition(
        code="HYDROGEN",
        label="Wasserstoff (Erzeugung, Speicherung, Transport)",
        nis2_group="Anhang I – hohe Kritikalitaet",
        nis2_annex='I',
        indicative_classification="Regelmaessig besonders wichtig / KRITIS-nah",
        score_bonus=6,
        reasoning="Wasserstoff ist seit NIS2 explizit als Teilsektor von Energie in Anhang I aufgefuehrt.",
        downstream_impact="Behandlung analog Energiesektor. Zusaetzlich Fokus auf Anlagensicherheit und Speicherinfrastruktur.",
        roadmap_focus=["Anlagensicherheit", "BCM", "Lieferkette"],
        key_domains=["BCM", "PHYS", "INC", "SUP"],
        kritis_related=True,
        kritis_note="Eigene KRITIS-Schwellenwerte koennen je nach nationaler Umsetzung gelten.",
    ),
    SectorDefinition(
        code="TRANSPORT",
        label="Transport und Verkehr",
        nis2_group="Anhang I – hohe Kritikalitaet",
        nis2_annex='I',
        indicative_classification="Regelmaessig besonders wichtig / KRITIS-nah",
        score_bonus=6,
        reasoning="Transport und Verkehr gehoeren zu den Sektoren mit hoher Kritikalitaet und sind in Deutschland oft KRITIS-nah.",
        downstream_impact="Roadmap priorisiert Betriebsstabilitaet, Wiederanlauf, physische Zugaenge und Vorfallsteuerung.",
        roadmap_focus=["Betriebsstabilitaet", "BCM", "Incident Management"],
        key_domains=["BCM", "PHYS", "INC", "SUP"],
        kritis_related=True,
        kritis_note="KRITIS-Schwellenwerte nach BSI-KritisV beachten (z.B. Flughaefen ab 20 Mio. Passagiere).",
    ),
    SectorDefinition(
        code="BANKING",
        label="Bankwesen",
        nis2_group="Anhang I – hohe Kritikalitaet",
        nis2_annex='I',
        indicative_classification="Regelmaessig besonders wichtig",
        score_bonus=6,
        reasoning="Bankwesen ist ein NIS-2-Sektor mit hoher Kritikalitaet; zugleich koennen sektorspezifische Regime relevant sein.",
        downstream_impact="Die App priorisiert Governance, IAM, Logging, Incident Management und verweist auf sektorale Ueberschneidungen.",
        roadmap_focus=["IAM", "Monitoring", "Governance"],
        key_domains=["IAM", "DETECT", "INC", "DOC"],
        special_regime="DORA-Ueberschneidung pruefen (Verordnung (EU) 2022/2554)",
    ),
    SectorDefinition(
        code="FINANCIAL_MARKET_INFRASTRUCTURE",
        label="Finanzmarktinfrastruktur",
        nis2_group="Anhang I – hohe Kritikalitaet",
        nis2_annex='I',
        indicative_classification="Regelmaessig besonders wichtig",
        score_bonus=6,
        reasoning="Finanzmarktinfrastruktur zaehlt zu den NIS-2-Sektoren mit hoher Kritikalitaet.",
        downstream_impact="Zusaetzlicher Fokus auf sektorspezifische Ueberschneidungen, Resilienz und Meldepflichten.",
        roadmap_focus=["Resilienz", "Meldewege", "Governance"],
        key_domains=["BCM", "INC", "DOC", "DETECT"],
        special_regime="DORA-Ueberschneidung pruefen (Verordnung (EU) 2022/2554)",
    ),
    SectorDefinition(
        code="HEALTH",
        label="Gesundheitswesen",
        nis2_group="Anhang I – hohe Kritikalitaet",
        nis2_annex='I',
        indicative_classification="Regelmaessig besonders wichtig / KRITIS-nah",
        score_bonus=6,
        reasoning="Gesundheitswesen ist ein Sektor mit hoher Kritikalitaet und in Deutschland haeufig eng mit KRITIS verknuepft.",
        downstream_impact="Roadmap priorisiert Verfuegbarkeit, Wiederanlauf, Lieferantensteuerung und Schutz sensibler Daten.",
        roadmap_focus=["BCM", "Lieferkette", "Kryptografie"],
        key_domains=["BCM", "SUP", "CRYPTO", "INC"],
        kritis_related=True,
        kritis_note="KRITIS-Schwellenwerte: z.B. 30.000 vollstationaere Faelle/Jahr fuer Krankenhaeuser.",
    ),
    SectorDefinition(
        code="DRINKING_WATER",
        label="Trinkwasser",
        nis2_group="Anhang I – hohe Kritikalitaet",
        nis2_annex='I',
        indicative_classification="Regelmaessig besonders wichtig / KRITIS-nah",
        score_bonus=6,
        reasoning="Trinkwasser faellt unter die NIS-2-Sektoren mit hoher Kritikalitaet und ist in Deutschland KRITIS-nah.",
        downstream_impact="Der Prozess staerkt BCM, physische Sicherheit, Angriffserkennung und Dienstleisterresilienz.",
        roadmap_focus=["BCM", "Physische Sicherheit", "Monitoring"],
        key_domains=["BCM", "PHYS", "DETECT", "SUP"],
        kritis_related=True,
        kritis_note="KRITIS-Schwellenwert: 500.000 versorgte Personen.",
    ),
    SectorDefinition(
        code="WASTEWATER",
        label="Abwasser",
        nis2_group="Anhang I – hohe Kritikalitaet",
        nis2_annex='I',
        indicative_classification="Regelmaessig besonders wichtig / KRITIS-nah",
        score_bonus=6,
        reasoning="Abwasser zaehlt zu den hochkritischen NIS-2-Sektoren und ist oft KRITIS-nah.",
        downstream_impact="Roadmap hebt Resilienz, Betriebsfaehigkeit, Monitoring und physische Kontrollen hervor.",
        roadmap_focus=["Resilienz", "Monitoring", "Physische Sicherheit"],
        key_domains=["BCM", "PHYS", "DETECT"],
        kritis_related=True,
        kritis_note="KRITIS-Schwellenwert: 500.000 angeschlossene Einwohner.",
    ),
    SectorDefinition(
        code="DIGITAL_INFRASTRUCTURE",
        label="Digitale Infrastruktur",
        nis2_group="Anhang I – hohe Kritikalitaet",
        nis2_annex='I',
        indicative_classification="Regelmaessig besonders wichtig",
        score_bonus=6,
        reasoning="Digitale Infrastruktur zaehlt zu den hochkritischen NIS-2-Sektoren.",
        downstream_impact="Die App priorisiert Monitoring, Incident Management, Lieferkette und Nachweisfuehrung fuer digitale Kernservices.",
        roadmap_focus=["Monitoring", "Incident Management", "Lieferkette"],
        key_domains=["DETECT", "INC", "SUP", "CLOUD"],
    ),
    SectorDefinition(
        code="ICT_SERVICE_MANAGEMENT",
        label="Verwaltung von IKT-Diensten (B2B / MSP / Rechenzentrum)",
        nis2_group="Anhang I – hohe Kritikalitaet",
        nis2_annex='I',
        indicative_classification="Haeufig wichtig bis besonders wichtig",
        score_bonus=6,
        reasoning="B2B-IKT-Dienstleister wie MSP oder Rechenzentren sind im NIS-2-Umfeld besonders relevant.",
        downstream_impact="Der weitere Prozess fokussiert staerker auf Secure Operations, Lieferkette, Logging und sichere Entwicklungs-/Betriebsprozesse.",
        roadmap_focus=["Secure Operations", "Logging", "Lieferkette", "SDLC"],
        key_domains=["DETECT", "SUP", "SDLC", "IAM", "CLOUD"],
    ),
    # F04: MSSP als eigene Kategorie (NIS2 Art. 6 Nr. 40)
    SectorDefinition(
        code="MSSP",
        label="Managed Security Service Provider (MSSP)",
        nis2_group="Anhang I – hohe Kritikalitaet",
        nis2_annex='I',
        indicative_classification="Haeufig wichtig bis besonders wichtig",
        score_bonus=6,
        reasoning="MSSPs sind in NIS2 Art. 6 Nr. 40 als eigene Einrichtungsart definiert und unterliegen erhoehten Anforderungen.",
        downstream_impact="Fokus auf SOC-Prozesse, Threat Detection, Incident Response, Kunden-SLAs und Nachweispflichten gegenueber regulierten Kunden.",
        roadmap_focus=["SOC-Prozesse", "Incident Response", "Kundennachweis"],
        key_domains=["DETECT", "INC", "SUP", "DOC", "CLOUD"],
    ),
    SectorDefinition(
        code="PUBLIC_ADMINISTRATION",
        label="Oeffentliche Verwaltung",
        nis2_group="Anhang I – hohe Kritikalitaet",
        nis2_annex='I',
        indicative_classification="Haeufig besonders wichtig",
        score_bonus=6,
        reasoning="Oeffentliche Verwaltung gehoert zu den NIS-2-Sektoren mit hoher Kritikalitaet.",
        downstream_impact="Roadmap legt zusaetzlichen Fokus auf Governance, Rollen, Meldewege und Dienstleistersteuerung.",
        roadmap_focus=["Governance", "Rollen", "Meldewege"],
        key_domains=["GOV", "DOC", "INC", "SUP"],
    ),
    SectorDefinition(
        code="SPACE",
        label="Weltraum",
        nis2_group="Anhang I – hohe Kritikalitaet",
        nis2_annex='I',
        indicative_classification="Haeufig besonders wichtig",
        score_bonus=6,
        reasoning="Weltraum ist in Anhang I der NIS-2-Richtlinie als Sektor mit hoher Kritikalitaet aufgefuehrt.",
        downstream_impact="Die App priorisiert Resilienz, Lieferkette und klare Verantwortlichkeiten fuer hochkritische Dienste.",
        roadmap_focus=["Resilienz", "Lieferkette", "Governance"],
        key_domains=["BCM", "SUP", "GOV", "DETECT"],
    ),
    SectorDefinition(
        code="POSTAL_COURIER",
        label="Post- und Kurierdienste",
        nis2_group="Anhang II – sonstige kritische Sektoren",
        nis2_annex='II',
        indicative_classification="Haeufig wichtige Einrichtung",
        score_bonus=4,
        reasoning="Post- und Kurierdienste gehoeren in der NIS-2-Systematik zu den sonstigen kritischen Sektoren.",
        downstream_impact="Der weitere Prozess priorisiert Lieferkettenkontrollen, BCM und Vorfallsteuerung.",
        roadmap_focus=["Lieferkette", "BCM", "Incident Management"],
        key_domains=["SUP", "BCM", "INC"],
    ),
    SectorDefinition(
        code="WASTE_MANAGEMENT",
        label="Abfallbewirtschaftung",
        nis2_group="Anhang II – sonstige kritische Sektoren",
        nis2_annex='II',
        indicative_classification="Haeufig wichtige Einrichtung",
        score_bonus=4,
        reasoning="Abfallbewirtschaftung ist Teil der sonstigen kritischen Sektoren nach NIS-2.",
        downstream_impact="Roadmap priorisiert Betriebsstabilitaet, Dienstleistersteuerung und physische Sicherheit.",
        roadmap_focus=["Betriebsstabilitaet", "Lieferkette", "Physische Sicherheit"],
        key_domains=["SUP", "PHYS", "BCM"],
    ),
    SectorDefinition(
        code="CHEMICALS",
        label="Chemie",
        nis2_group="Anhang II – sonstige kritische Sektoren",
        nis2_annex='II',
        indicative_classification="Haeufig wichtige Einrichtung",
        score_bonus=4,
        reasoning="Produktion, Herstellung und Handel mit chemischen Stoffen zaehlen zu den sonstigen kritischen Sektoren.",
        downstream_impact="Der Prozess legt mehr Gewicht auf Lieferkette, physische Sicherheit, Wiederanlauf und Schutz von Produktionsprozessen.",
        roadmap_focus=["Lieferkette", "Physische Sicherheit", "Wiederanlauf"],
        key_domains=["SUP", "PHYS", "BCM"],
    ),
    SectorDefinition(
        code="FOOD",
        label="Lebensmittel",
        nis2_group="Anhang II – sonstige kritische Sektoren",
        nis2_annex='II',
        indicative_classification="Haeufig wichtige Einrichtung",
        score_bonus=4,
        reasoning="Produktion, Verarbeitung und Vertrieb von Lebensmitteln gehoeren zu den sonstigen kritischen Sektoren.",
        downstream_impact="Roadmap priorisiert Lieferkette, BCM und Wiederanlauf sowie verlaessliche Dokumentation.",
        roadmap_focus=["Lieferkette", "Resilienz", "Dokumentation"],
        key_domains=["SUP", "BCM", "DOC"],
    ),
    SectorDefinition(
        code="MANUFACTURING",
        label="Verarbeitendes Gewerbe / Herstellung von Waren",
        nis2_group="Anhang II – sonstige kritische Sektoren",
        nis2_annex='II',
        indicative_classification="Haeufig wichtige Einrichtung",
        score_bonus=4,
        reasoning="Bestimmte Bereiche des verarbeitenden Gewerbes fallen unter die sonstigen kritischen Sektoren der NIS-2-Systematik.",
        downstream_impact="Die App legt mehr Gewicht auf Lieferkette, Lifecycle, Patchen und Betriebsresilienz.",
        roadmap_focus=["Lifecycle", "Patchmanagement", "Lieferkette"],
        key_domains=["SDLC", "CYBER", "SUP", "BCM"],
    ),
    SectorDefinition(
        code="DIGITAL_PROVIDERS",
        label="Anbieter digitaler Dienste",
        nis2_group="Anhang II – sonstige kritische Sektoren",
        nis2_annex='II',
        indicative_classification="Haeufig wichtige Einrichtung",
        score_bonus=4,
        reasoning="Anbieter digitaler Dienste gehoeren zu den sonstigen kritischen Sektoren.",
        downstream_impact="Roadmap priorisiert Cloud, Monitoring, Incident Management und sichere Entwicklungsprozesse.",
        roadmap_focus=["Cloud", "Monitoring", "SDLC"],
        key_domains=["CLOUD", "DETECT", "INC", "SDLC"],
    ),
    SectorDefinition(
        code="RESEARCH",
        label="Forschung",
        nis2_group="Anhang II – sonstige kritische Sektoren",
        nis2_annex='II',
        indicative_classification="Teilweise wichtige Einrichtung",
        score_bonus=4,
        reasoning="Forschung zaehlt in der NIS-2-Systematik zu den sonstigen kritischen Sektoren.",
        downstream_impact="Der Prozess fokussiert staerker auf Schutz sensibler Daten, Kollaboration mit Dritten und Governance.",
        roadmap_focus=["Daten- und IP-Schutz", "Lieferkette", "Governance"],
        key_domains=["CRYPTO", "SUP", "DOC", "GOV"],
    ),
    SectorDefinition(
        code="OTHER",
        label="Sonstige / nicht klar zuordenbar",
        nis2_group="Nicht eindeutig regulierungsnah",
        nis2_annex='',
        indicative_classification="ISO-27001-first / Einzelfallpruefung",
        score_bonus=0,
        reasoning="Der gewaehlte Sektor ist nicht direkt als NIS-2-Sektor vorgegeben; Relevanz kann dennoch ueber Dienste, Groesse oder Lieferkettenrolle entstehen.",
        downstream_impact="Die App legt den Schwerpunkt eher auf ISO-27001-Readiness, kann aber bei weiteren Indikatoren NIS2-Naehe ausweisen.",
        roadmap_focus=["Scope", "Register", "Basismassnahmen"],
        key_domains=["GOV", "PROC", "DOC"],
    ),
]

SECTOR_MAP: Dict[str, SectorDefinition] = {item.code: item for item in SECTOR_DEFINITIONS}
SECTOR_CHOICES = [(item.code, f"{item.label} ({item.nis2_group})") for item in SECTOR_DEFINITIONS]


def get_sector_choices():
    return SECTOR_CHOICES


def get_sector_definition(code: str | None) -> SectorDefinition:
    return SECTOR_MAP.get(code or "", SECTOR_MAP["OTHER"])
