# Generated by Django 5.2.12 on 2026-03-09 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUFFICIENT', 'Vorhanden und ausreichend'), ('PARTIAL', 'Vorhanden, aber unvollständig'), ('INFORMAL', 'Informal vorhanden'), ('DOCUMENTED_NOT_IMPLEMENTED', 'Dokumentiert, aber nicht umgesetzt'), ('IMPLEMENTED_NO_EVIDENCE', 'Umgesetzt, aber nicht nachweisbar'), ('MISSING', 'Fehlt vollständig')], default='MISSING', max_length=32)),
                ('documented', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('communicated', models.BooleanField(default=False)),
                ('implemented', models.BooleanField(default=False)),
                ('effective', models.BooleanField(default=False)),
                ('evidenced', models.BooleanField(default=False)),
                ('reviewed_at', models.DateField(blank=True, null=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='organizations.businessunit')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_processes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='organizations.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
