FROM --platform=linux/amd64 docker.io/library/rust:1.97-bookworm@sha256:77fac8b98f9f46062bb680b6d25d5bcaabfc400143952ebc572e924bcbedc3fa AS builder

ARG SOURCE_DATE_EPOCH
WORKDIR /usr/src/iscy/rust/iscy-backend

ENV CARGO_INCREMENTAL=0 \
    CARGO_PROFILE_RELEASE_DEBUG=0 \
    CARGO_PROFILE_RELEASE_STRIP=symbols \
    RUSTFLAGS="--remap-path-prefix=/usr/local/cargo/registry=/usr/src/cargo-registry --remap-path-prefix=/usr/local/cargo/git=/usr/src/cargo-git"

COPY rust/iscy-backend/Cargo.toml rust/iscy-backend/Cargo.lock ./
COPY rust/iscy-backend/src ./src
COPY rust/iscy-backend/seeds ./seeds
COPY deploy /usr/src/iscy/deploy
COPY flake.lock /usr/src/iscy/flake.lock

RUN test -n "$SOURCE_DATE_EPOCH" \
    && case "$SOURCE_DATE_EPOCH" in *[!0-9]*) exit 1 ;; esac \
    && test "$(rustc --version | cut -d ' ' -f 2)" = "1.88.0" \
    && SOURCE_DATE_EPOCH="$SOURCE_DATE_EPOCH" \
       cargo build --release --locked --bin iscy-backend

FROM scratch AS artifact
COPY --from=builder /usr/src/iscy/rust/iscy-backend/target/release/iscy-backend /iscy-backend
