# Generated by Django 5.2.12 on 2026-03-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('wizard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('executive_summary', models.TextField(blank=True)),
                ('applicability_result', models.CharField(blank=True, max_length=255)),
                ('iso_readiness_percent', models.PositiveIntegerField(default=0)),
                ('nis2_readiness_percent', models.PositiveIntegerField(default=0)),
                ('cra_readiness_percent', models.PositiveIntegerField(default=0)),
                ('ai_act_readiness_percent', models.PositiveIntegerField(default=0)),
                ('iec62443_readiness_percent', models.PositiveIntegerField(default=0)),
                ('iso_sae_21434_readiness_percent', models.PositiveIntegerField(default=0)),
                ('regulatory_matrix_json', models.JSONField(blank=True, default=dict)),
                ('product_security_json', models.JSONField(blank=True, default=dict)),
                ('top_gaps_json', models.JSONField(blank=True, default=list)),
                ('top_measures_json', models.JSONField(blank=True, default=list)),
                ('roadmap_summary', models.JSONField(blank=True, default=list)),
                ('domain_scores_json', models.JSONField(blank=True, default=list)),
                ('next_steps_json', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='wizard.assessmentsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='organizations.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
