# Generated by Django 5.2.12 on 2026-03-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsnapshot',
            name='compliance_versions_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportsnapshot',
            name='kritis_readiness_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
