# Generated by Django 5.2.12 on 2026-03-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('weight', models.PositiveIntegerField(default=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('text', models.CharField(max_length=500)),
                ('help_text', models.TextField(blank=True)),
                ('why_it_matters', models.TextField(blank=True)),
                ('question_kind', models.CharField(choices=[('APPLICABILITY', 'Betroffenheit'), ('MATURITY', 'Reifegrad')], max_length=20)),
                ('wizard_step', models.CharField(choices=[('applicability', 'Betroffenheit'), ('maturity', 'Reifegrad')], max_length=20)),
                ('weight', models.PositiveIntegerField(default=10)),
                ('is_required', models.BooleanField(default=True)),
                ('applies_to_iso27001', models.BooleanField(default=True)),
                ('applies_to_nis2', models.BooleanField(default=False)),
                ('applies_to_cra', models.BooleanField(default=False)),
                ('applies_to_ai_act', models.BooleanField(default=False)),
                ('applies_to_iec62443', models.BooleanField(default=False)),
                ('applies_to_iso_sae_21434', models.BooleanField(default=False)),
                ('applies_to_product_security', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='catalog.assessmentdomain')),
            ],
            options={
                'ordering': ['wizard_step', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_score_threshold', models.IntegerField(default=2)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('CRITICAL', 'Kritisch'), ('HIGH', 'Hoch'), ('MEDIUM', 'Mittel'), ('LOW', 'Niedrig')], default='MEDIUM', max_length=16)),
                ('effort', models.CharField(choices=[('SMALL', 'Klein'), ('MEDIUM', 'Mittel'), ('LARGE', 'Groß')], default='MEDIUM', max_length=16)),
                ('measure_type', models.CharField(choices=[('ORGANIZATIONAL', 'Organisatorisch'), ('TECHNICAL', 'Technisch'), ('DOCUMENTARY', 'Dokumentarisch')], default='ORGANIZATIONAL', max_length=20)),
                ('owner_role', models.CharField(blank=True, max_length=64)),
                ('target_phase', models.CharField(blank=True, max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_rules', to='catalog.assessmentquestion')),
            ],
            options={
                'ordering': ['question', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_na', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.assessmentquestion')),
            ],
            options={
                'ordering': ['question', 'sort_order'],
                'unique_together': {('question', 'slug')},
            },
        ),
    ]
