# Generated by Django 5.2.12 on 2026-03-09 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('phase', models.CharField(choices=[('applicability', 'Betroffenheit'), ('scope', 'Scope'), ('processes', 'Prozesse'), ('assessment', 'Bewertung'), ('mapping', 'Mapping'), ('measures', 'Maßnahmen'), ('evidence', 'Evidenz'), ('review', 'Review')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('why_it_matters', models.TextField()),
                ('required_inputs', models.TextField(blank=True)),
                ('expected_outputs', models.TextField(blank=True)),
                ('definition_of_done', models.TextField(blank=True)),
                ('route_name', models.CharField(blank=True, max_length=100)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TenantJourneyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('next_action_text', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_tenants', to='guidance.guidancestep')),
                ('last_completed_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_completed_for_tenants', to='guidance.guidancestep')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey_state', to='organizations.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
