# Generated by Django 5.2.12 on 2026-03-09 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('operation_countries', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(blank=True, choices=[('ENERGY', 'Energie (Anhang I – hohe Kritikalitaet)'), ('HYDROGEN', 'Wasserstoff (Erzeugung, Speicherung, Transport) (Anhang I – hohe Kritikalitaet)'), ('TRANSPORT', 'Transport und Verkehr (Anhang I – hohe Kritikalitaet)'), ('BANKING', 'Bankwesen (Anhang I – hohe Kritikalitaet)'), ('FINANCIAL_MARKET_INFRASTRUCTURE', 'Finanzmarktinfrastruktur (Anhang I – hohe Kritikalitaet)'), ('HEALTH', 'Gesundheitswesen (Anhang I – hohe Kritikalitaet)'), ('DRINKING_WATER', 'Trinkwasser (Anhang I – hohe Kritikalitaet)'), ('WASTEWATER', 'Abwasser (Anhang I – hohe Kritikalitaet)'), ('DIGITAL_INFRASTRUCTURE', 'Digitale Infrastruktur (Anhang I – hohe Kritikalitaet)'), ('ICT_SERVICE_MANAGEMENT', 'Verwaltung von IKT-Diensten (B2B / MSP / Rechenzentrum) (Anhang I – hohe Kritikalitaet)'), ('MSSP', 'Managed Security Service Provider (MSSP) (Anhang I – hohe Kritikalitaet)'), ('PUBLIC_ADMINISTRATION', 'Oeffentliche Verwaltung (Anhang I – hohe Kritikalitaet)'), ('SPACE', 'Weltraum (Anhang I – hohe Kritikalitaet)'), ('POSTAL_COURIER', 'Post- und Kurierdienste (Anhang II – sonstige kritische Sektoren)'), ('WASTE_MANAGEMENT', 'Abfallbewirtschaftung (Anhang II – sonstige kritische Sektoren)'), ('CHEMICALS', 'Chemie (Anhang II – sonstige kritische Sektoren)'), ('FOOD', 'Lebensmittel (Anhang II – sonstige kritische Sektoren)'), ('MANUFACTURING', 'Verarbeitendes Gewerbe / Herstellung von Waren (Anhang II – sonstige kritische Sektoren)'), ('DIGITAL_PROVIDERS', 'Anbieter digitaler Dienste (Anhang II – sonstige kritische Sektoren)'), ('RESEARCH', 'Forschung (Anhang II – sonstige kritische Sektoren)'), ('OTHER', 'Sonstige / nicht klar zuordenbar (Nicht eindeutig regulierungsnah)')], default='OTHER', max_length=64)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('annual_revenue_million', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_sheet_million', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('critical_services', models.TextField(blank=True)),
                ('supply_chain_role', models.CharField(blank=True, max_length=255)),
                ('nis2_relevant', models.BooleanField(default=False)),
                ('kritis_relevant', models.BooleanField(default=False)),
                ('develops_digital_products', models.BooleanField(default=False)),
                ('uses_ai_systems', models.BooleanField(default=False)),
                ('ot_iacs_scope', models.BooleanField(default=False)),
                ('automotive_scope', models.BooleanField(default=False)),
                ('psirt_defined', models.BooleanField(default=False)),
                ('sbom_required', models.BooleanField(default=False)),
                ('product_security_scope', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('service_description', models.TextField(blank=True)),
                ('criticality', models.CharField(default='MEDIUM', max_length=32)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_suppliers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='organizations.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(max_length=100)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='organizations.legalentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='organizations.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='legalentity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entities', to='organizations.tenant'),
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_business_units', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_units', to='organizations.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
